FROM grpc/python:1.4
ADD . /microservices-grpc-go-python
WORKDIR /microservices-grpc-go-python/pyton
RUN pip install --upgrade pip

RUN pip install -r Requirements.txt
CMD ["python", "main.py", "9500"]