FROM grpc/python
ADD . /app/src/Proyecto2/
WORKDIR /app/src/Proyecto2/servidor_Py/Comunicado
RUN pip install --upgrade pip \
 && pip install grpcio grpcio-tools
RUN pip install -r Requeriments.txt
CMD ["python", "servidor.py", "11443"]