# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comunicacion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comunicacion.proto',
  package='comunicacion',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63omunicacion.proto\x12\x0c\x63omunicacion\"\x17\n\x07llamada\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2E\n\x0b\x43omunicando\x12\x36\n\x04\x63\x61ll\x12\x15.comunicacion.llamada\x1a\x15.comunicacion.llamada\"\x00\x62\x06proto3'
)




_LLAMADA = _descriptor.Descriptor(
  name='llamada',
  full_name='comunicacion.llamada',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='comunicacion.llamada.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['llamada'] = _LLAMADA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

llamada = _reflection.GeneratedProtocolMessageType('llamada', (_message.Message,), {
  'DESCRIPTOR' : _LLAMADA,
  '__module__' : 'comunicacion_pb2'
  # @@protoc_insertion_point(class_scope:comunicacion.llamada)
  })
_sym_db.RegisterMessage(llamada)



_COMUNICANDO = _descriptor.ServiceDescriptor(
  name='Comunicando',
  full_name='comunicacion.Comunicando',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=61,
  serialized_end=130,
  methods=[
  _descriptor.MethodDescriptor(
    name='call',
    full_name='comunicacion.Comunicando.call',
    index=0,
    containing_service=None,
    input_type=_LLAMADA,
    output_type=_LLAMADA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMUNICANDO)

DESCRIPTOR.services_by_name['Comunicando'] = _COMUNICANDO

# @@protoc_insertion_point(module_scope)
