FROM golang:1.11-stretch
ADD . /app/src/Proyecto2/
ENV GOPATH=/app

RUN go get -u github.com/gorilla/mux
RUN go get -u github.com/streadway/amqp

WORKDIR /app/src/Proyecto2/GolangServer/

CMD ["go", "run", "send.go"]