# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comunicacion_pb2 as comunicacion__pb2


class ComunicandoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call = channel.unary_unary(
                '/comunicacion.Comunicando/call',
                request_serializer=comunicacion__pb2.llamada.SerializeToString,
                response_deserializer=comunicacion__pb2.llamada.FromString,
                )


class ComunicandoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComunicandoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call': grpc.unary_unary_rpc_method_handler(
                    servicer.call,
                    request_deserializer=comunicacion__pb2.llamada.FromString,
                    response_serializer=comunicacion__pb2.llamada.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comunicacion.Comunicando', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Comunicando(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comunicacion.Comunicando/call',
            comunicacion__pb2.llamada.SerializeToString,
            comunicacion__pb2.llamada.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
